# Based on https://keepachangelog.com/en/1.1.0/

changelog:

  exclude:
    authors:
      - dependabot[bot]
      - github-actions[bot]

  categories:

    # For new features
    - title: Added
      labels:
        - enhancement

    # For changes in existing functionality
    - title: Changed
      labels:
        - change

    # For soon-to-be removed features
    - title: Deprecated
      labels:
        - deprecation

    # For now removed features
    - title: Removed
      labels:
        - removed

    # For any bug fixes
    - title: Fixed
      labels:
        - bug

    # In case of vulnerabilities
    - title: Security
      labels:
        - security

    # For other changes
    - title: Other
      labels:
        - "*"
